name: BanVote
author: slipcor
main: net.slipcor.banvote.BanVotePlugin
version: 0.1.4.1
website: http://dev.bukkit.org/server-mods/banvote
commands:
    banvote:
        description: vote for banning a player
        usage: |
            /banvote help | detailed usage help
            /banvote [playername] [reason] | start vote
            /banvote [+|yes|true] | vote for ban
            /banvote [-|no|false] | vote against ban
        permission: banvote.vote
    mutevote:
        description: vote for muting a player
        usage: |
            /mutevote help | detailed usage help
            /mutevote [playername] [reason] | start vote
            /mutevote [+|yes|true] | vote for mute
            /mutevote [-|no|false] | vote against mute
        permission: mutevote.vote
    kickvote:
        description: vote for kicking a player
        usage: |
            /kickvote help | detailed usage help
            /kickvote [playername] [reason] | start vote
            /kickvote [+|yes|true] | vote for kick
            /kickvote [-|no|false] | vote against kick
        permission: kickvote.vote
    customvote:
        description: vote for committing a command (on a player)
        usage: |
            /customvote help | detailed usage help
            /customvote [playername] [type] [reason] | start vote
            /customvote [+|yes|true] | vote for kick
            /customvote [-|no|false] | vote against kick
        permission: customvote.vote
    release:
        description: unban/mute a player
        usage: |
            /release [#] | unban vote #
            /release list | list all bans/mutes
permissions:
    banvote.admin:
        description: Allows you to unban
        default: op
    banvote.novote:
        description: Prevents a vote on a player
        default: op
    banvote.cmd:
        description: Allows you to start a ban vote
        default: true
    customvote.cmd:
        description: Allows you to start a custom vote
        default: true
    kickvote.cmd:
        description: Allows you to start a kick vote
        default: true
    mutevote.cmd:
        description: Allows you to start a mute vote
        default: true
    banvote.vote:
        description: Allows you to vote
        default: true
    mutevote.vote:
        description: Allows you to vote
        default: true
    kickvote.vote:
        description: Allows you to vote
        default: true